services:
  app:
    image: donde-me-siento:latest
    container_name: donde-me-siento
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./data:/app/data

  reverse-proxy:
    build:
      context: ./deploy/reverse-proxy
    container_name: donde-me-siento-proxy
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/reverse-proxy/certs:/etc/nginx/certs
