services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: donde-me-siento:latest
    container_name: donde-me-siento
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./data:/app/data

  reverse-proxy:
    build:
      context: ./deploy/reverse-proxy
    container_name: donde-me-siento-proxy
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt      
      - ./certbot/www:/var/www/certbot  

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
